{
 "title": "RNode COMM rate",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RSpace operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(span_processing_time_seconds_count{operation=~\"rchain.rspace.consume\"}[1m])",
     "legendFormat": "Consume@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "rate(span_processing_time_seconds_count{operation=~\"rchain.rspace.produce\"}[1m])",
     "legendFormat": "Produce@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "rate(span_processing_time_seconds_count{operation=~\"rchain.rspace.install\"}[1m])",
     "legendFormat": "Install@{{exported_instance}}@{{exported_job}}"
    }
   ]
  },
  {
   "title": "RSpace COMM events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rspace_comm_consume_total[1m])",
     "legendFormat": " Consume COMM@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "rate(rspace_comm_produce_total[1m])",
     "legendFormat": "Produce COMM@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "sum(rate(rspace_comm_produce_total[10s]))",
     "legendFormat": "comm rate"
    }
   ]
  },
  {
   "title": "ReplayRSpace operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(span_processing_time_seconds_count{operation=~\"rchain.rspace.replay.consume\"}[1m])",
     "legendFormat": "Consume@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "rate(span_processing_time_seconds_count{operation=~\"rchain.rspace.replay.produce\"}[1m])",
     "legendFormat": "Produce@{{exported_instance}}@{{exported_job}}"
    }
   ]
  },
  {
   "title": "ReplayRSpace COMM event",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(replayrspace_comm_consume_total[1m])",
     "legendFormat": "Consume COMM@{{exported_instance}}@{{exported_job}}"
    },
    {
     "expr": "rate(replayrspace_comm_produce_total[1m])",
     "legendFormat": "Produce COMM@{{exported_instance}}@{{exported_job}}"
    }
   ]
  }
 ]
}