{
 "title": "Testnet1 CollectD",
 "time": { "from": "2019-03-21T05:27:04.927Z", "to": "2019-03-21T06:27:04.927Z" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Memory ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "contextswitch_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network RX/TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_rx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "!=", "value": "lo" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "interface_tx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "!=", "value": "lo" }
     ]
    }
   ]
  }
 ]
}